name: Test

on:
  push:
    branches:
      - master
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      RUST_LOG: tapyrusd=debug
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        feature:
          [
            "0_5_2",
            "0_5_1",
          ]
    steps:
      - run: df -h
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.feature }}${{ matrix.os }}
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --features ${{ matrix.feature }}
      - run: echo "TAPYRUSD_EXE=$(find ./target/debug -name tapyrusd)" >> $GITHUB_ENV
      - run: cargo test

  cosmetics:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings

  rust-version:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        toolchain: ["1.56.1", "stable", "nightly"]

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.version }}1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: |
          cargo update
          cargo update -p tempfile --precise 3.3.0
          cargo update -p log --precise 0.4.18
        if: ${{ matrix.toolchain == '1.56.1' }}
      - run: cargo build

  build-nix:
    runs-on: ubuntu-20.04
    env:
      FNAME: tapyrus-core-0.5.2-x86_64-linux-gnu.tar.gz
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: echo "TAPYRUSD_TARBALL_FILE=./${FNAME}" >> $GITHUB_ENV
      - run: cargo build --features 0_5_2 && exit 1 || exit 0
      - run: wget https://github.com/chaintope/tapyrus-core/releases/download/v0.5.2/${FNAME}
      - run: cargo build --features 0_5_2
